package eu.theeconomystupid.engine;

public enum MessageConditionType {
    VALUE_EQ,
    VALUE_GT,
    VALUE_GE,
    VALUE_LT,
    VALUE_LE,
    ABSOLUTE_DELTA_EQ,
    ABSOLUTE_DELTA_GT,
    ABSOLUTE_DELTA_GE,
    ABSOLUTE_DELTA_LT,
    ABSOLUTE_DELTA_LE,
    RELATIVE_DELTA_EQ,
    RELATIVE_DELTA_GT,
    RELATIVE_DELTA_GE,
    RELATIVE_DELTA_LT,
    RELATIVE_DELTA_LE,
    VALUE_CONTAINS
}
